### ISSUE TITLE
Reverse ordering after normalize application

### ISSUE THREAD

**Issue by rsales** [yury-dymov/json-api-normalizer#52] opened 2019-02-05 16:02 UTC
Hello, I'm currently working on. A project using the RoR to construct the **API.JSON** and we are consuming it using **VUE.js** to consume this api built in **RoR**.

Well we have the following problems, the API when only consumed it comes in the correct ordering of the data after passing through the `normalizer (json)` method it happens that it reorders the structure of the API according to the model presented in the images...

![screen shot 2019-02-05 at 12 25 04](https://user-images.githubusercontent.com/4354492/52279929-d2eef700-2941-11e9-8b4a-208b1026ba9d.png)

![screen shot 2019-02-05 at 14 26 06](https://user-images.githubusercontent.com/4354492/52287835-12254400-2952-11e9-96ff-4228ea25c21c.png)

![screen shot 2019-02-05 at 12 25 34](https://user-images.githubusercontent.com/4354492/52279941-d84c4180-2941-11e9-9d7d-4c1ea574b258.png)

I would like to know if there would be any way to keep the original ordering or maybe implement a `.revert()`.

The current code used within **VUEX/AXIOS** is like this...

```
api({
  url: <API-URL>,
  method: 'get'
}).then(async (vacancies) =>  (
    console.log('JSON:', vacancies.data.vacancies),
    console.log('Normalizer', normalize(vacancies.data.vacancies).vacancy, { meta: vacancies.data.vacancies}),

    // List vacancies
    commit('SET_VACANCIES', normalize(vacancies.data.vacancies)),
  ))
  .catch(error => {
    console.log(error)
    this.errored = true
  })
  .finally(() => console.log("Finish Loading"))
```

**Note:** Currently none of the previous answers have been enlightening.

**Comment by rsales** [comment] 2019-02-07 16:47
I opened the question in [StackOverflow](https://stackoverflow.com/questions/54575660/reverse-ordering-after-normalize-application-json-api-normalizer)

**Comment by yury-dymov** [comment] 2019-02-07 16:53
Hi @rsales, this is duplicate of #24, #28, #37, #40, and #43 .
This is covered in README and article mentioned in README.

**Closed by yury-dymov** 2019-02-07 16:53 UTC
