### ISSUE TITLE
Suggestion: Allow 'meta' with relationships

### ISSUE THREAD

**Issue by SirLamer** [yury-dymov/json-api-normalizer#25] opened 2017-11-26 01:40 UTC
Per the API spec, you can have a 'meta' property alongside the 'data' property in a relationship. Right now the normalizer scrubs this out. I intend to submit a PR to correct this but am posting here first to make sure there is an appetite for accepting this, or in case there are any expectations.

**Comment by yury-dymov** [comment] 2017-11-27 17:28
Sounds like duplicate of https://github.com/yury-dymov/json-api-normalizer/commit/4cfd5cca58e9da32a49c8fa65ce99b84ceb792e1

If something is missing, feel free to fix it though :)

**Comment by SirLamer** [comment] 2017-11-27 17:58
That issue only copies the metadata on the resource-level. It does not address relationship metadata.

I have implemented the relationship metadata handling which I intend to submit as a PR shortly.

Also at the moment it is not performing camelCase conversion on that resource metadata, my sense is that it should however that is potentially a breaking change so I have not affected it there.

**Closed** 2017-11-29 18:59 UTC
